# Generated by Django 3.2 on 2023-08-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=254, unique=True)),
                ('f_name', models.CharField(max_length=300)),
                ('sex', models.BooleanField(default=0)),
                ('age', models.CharField(max_length=8)),
                ('code', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
