# Generated by Django 4.2.3 on 2023-08-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="state",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=1)),
                ("second", models.CharField(max_length=1)),
                ("third", models.CharField(max_length=1)),
                ("fourth", models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="code",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="f_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="group",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.CharField(max_length=1),
        ),
    ]
