# Generated by Django 3.2 on 2023-08-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_patient_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
    ]
